### PR TITLE
sub sections for Youtube Playlists

### PR DESCRIPTION
**Pull request by CrandellWS**
You can see a full working example: 

http://www.amazon.com/CrandellWS-Game-Making-Tutorials/dp/B017GCINGM

The full source for the app is on GitHub:
http://github.com/CrandellWS/Unity-Focus/

and the Amazon Web App url is:
http://crandellws.github.io/Unity-Focus/

Any how it is the basic setup and guide as exampled by Amazon:
https://github.com/CrandellWS/web-app-starter-kit-for-fire-tv

It is just a matter of setting the right config to pull the videos from your Youtube Channel. 

The config for the previously mentioned app is:
https://github.com/CrandellWS/Unity-Focus/blob/gh-pages/js/init.js

Let me know.

### CODE REVIEW

**Comment by CrandellWS** [comment]
This issue should close #29 the only thing not included in pull that is needed is the config settings like shown:

https://github.com/gkbroderick/web-app-starter-kit-for-fire-tv/commit/67654c6458477e3bb5bef83153060a3dac79d26b/src/projects/youtube-subcategories/init.js#diff-a702cdc48a4c63e95756e3932af0dae9R15


            {
                type: "multiPlaylists",
                ids: ["PLhr1KZpdzukf6YADEpM6nFEZs7VDhEs5U",
                        "PLhr1KZpdzukeiCFgRccZ677GhHoP1OD8S",
                        "PLhr1KZpdzukeEDdaSY-HHJuX30WsoGhuW"
                    ],
                title: "Many Playlists"
            },

**Comment by CrandellWS** [comment]
pull request summary is mentioned in https://github.com/amzn/web-app-starter-kit-for-fire-tv/issues/26#issuecomment-203131073

**Comment by onlyinmystreams** [comment]
I have multilists before a playlist and it seems to be ignoring multilists. It does not show multilist anywhere on the app and only displays playlist.

```
channels: [
            {
            type: "multiPlaylists",
            ids: ["PLuaEUesstmAnCxHN34P-Lf7W0YK32XMp_",
                    "PLuaEUesstmAlX15juYdOElFM5zGHcVEeq",
                    "PLuaEUesstmAmNV03WhBuBDLPmlWWmjdhb"
                ],
            title: "Many Playlists"
            },
            {
                type: "playlist",
                id: "PLuaEUesstmAnwBl4Wuksce2Qg0UsLr_DZ",
                title: "What's On"
            }
```

**Comment by CrandellWS** [comment]
making change concise new pull request  #56

**Pull request closed without merging**
